[package]
name = "rust-trends"
version = "0.1.0"
authors = ["Robert Vally <rvally@gmail.com>"]

[dependencies]
#clippy = "*"
chrono = "*"
hyper = "*"
serde = "*"
serde_json = "*"
clap = "*"
rusqlite = "*"
